# Generated by Django 4.2.2 on 2025-02-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_namer",
            new_name="phone_number",
        ),
    ]
